name: Install dependencies
runs:
  using: composite
  steps:
    - name: Install pip and python
      shell: bash -el {0}
      run: |
        apt-get update
        apt-get install -y python3-pip
        python3 -m pip install -U pip
        python3 -m pip install scipy
        python3 -c "import scipy"