name: Build docs

on:
  workflow_run:
    workflows: [Test package]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      # Directory that will be published on github pages
      PUBLISH_DIR: ./_build/html
    if: github.event.workflow_run.conclusion == 'success'
  
    steps:

      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install ".[test,docs]"

      - name: Build docs
        run: 	jupyter book build -W .
  
      # Based on: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
      - name: 'Download coverage artifact'
        uses: actions/github-script@v6.4.0
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "code-coverage-report"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/code-coverage-report.zip`, Buffer.from(download.data));

      - name: Unzip artifact
        run: |
          unzip code-coverage-report.zip -d ${{ env.PUBLISH_DIR }}/code-coverage-report

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.PUBLISH_DIR }}

  