name: Build docs

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      # Directory that will be published on github pages
      PUBLISH_DIR: ./_build/html
  
    steps:

      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install ".[test,docs]"

      - name: Build docs
        run: 	jupyter book build -W .


      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ${{ env.PUBLISH_DIR }}
          if-no-files-found: error
