name: Test package

on:
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - main
  workflow_dispatch:
  workflow_call:

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"
jobs:
  check-code:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      # This action sets the current path to the root of your github repo
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install code"
        run: python -m pip install .[test]

      - name: Flake8 code
        run: python -m flake8

      - name: Mypy check
        run: python -m mypy

  test-code:
    # This code depends on the result of check-code
    needs: check-code
 

    strategy:
      matrix:
        os: [ubuntu-22.04]
        #python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ matrix.python-version }}


      - name: "Install mypackage"
        run: pip install .[test]

      - name: Run tests
        run: |
          python -m pytest

      # - name: Upload coverage report as artifact
      #   if: matrix.os == 'ubuntu-22.04' && matrix.python-version == '3.11'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: code-coverage-report
      #     path: htmlcov
      #     if-no-files-found: error
